# Generated by Django 6.1 on 2026-08-26 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=16)),
                ('notification_type', models.CharField(choices=[('ORDER_CONFIRMATION', 'Order Confirmation'), ('KEY_DELIVERY', 'License Key Delivery'), ('ACTIVATION_HELP', 'Activation Assistance')], max_length=32)),
                ('recipient', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('was_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sales.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
