# Generated by Django 6.1 on 2026-08-26 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('RETAIL', 'Retail'), ('OEM', 'OEM'), ('MAK', 'MAK (Multiple Activation Key)'), ('VOLUME', 'Volume License')], max_length=16)),
                ('key_code', models.CharField(max_length=64, unique=True)),
                ('region', models.CharField(default='GLOBAL', max_length=32)),
                ('activation_limit', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD', 'Sold'), ('REVOKED', 'Revoked')], default='AVAILABLE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_keys', to='sales.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_keys', to='catalog.softwareproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(max_length=128)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('license_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='licensing.licensekey')),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='licensekey',
            index=models.Index(fields=['product', 'license_type', 'status'], name='licensing_l_product_f3fa12_idx'),
        ),
    ]
